### ISSUE TITLE
Using the -t switch alone result in the script trying to upload nothing

### ISSUE THREAD

**Issue by bicobus** [BobbyWibowo/uguush#1]
### Description

One could assume the -t switch can be used to set and save the token and use it that way, which bypass the failsafe about the "no argument given" :
https://github.com/BobbyWibowo/uguush/blob/18da63b36380c4827d3224188d8e1a5817a009b0/uguush#L344

The `localFile` variable isn't being checked and is assumed to be initialized.

### How to reproduce

```
uguush -t <snip>
Try #1... [OK]
File has been uploaded: 
rm:  cannot remove '': No such file or directory
```

**Comment by BobbyWibowo** [comment]
Whoops, sorry for the late respond to this issue. Seen it while I was outside from email notification back then, and ended up forgetting about it ever since, lmao.
Should be fixed in 6f6ca7076572fc9e9841321ee463b81ffb8e602c.
