### ISSUE TITLE
How to upload multiple photos to Fiery at once?

### ISSUE THREAD

**Issue by sideloading** [BobbyWibowo/uguush#3]
I would like to bulk upload images, what is the best method of doing this?

Current command I'm using:

```bash
uguush -o fiery -t <token> -a <id> -u pic/1 image at a time.jpg
```

**Comment by BobbyWibowo** [comment]
You're better off using `curl`, or the likes, directly for that purpose
e.g.
```bash
curl http://domain.tld/api/upload \
-F "files[]=@/path/to/file1.ext" \
-F "files[]=@/path/to/file2.ext" \
-H "token: TOKEN" \
-H "albumid: ID"
```

`uguush` is intended as a helper script for third-party utilities, such as OS-wide global shortcuts, hence the philosophy of only supporting single file uploads
